name: Price Parser

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  parse-prices:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Cache Puppeteer
      uses: actions/cache@v3
      id: puppeteer-cache
      with:
        path: |
          ~/.cache/puppeteer
          node_modules
        key: ${{ runner.os }}-puppeteer-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-puppeteer-

    - name: Install dependencies
      run: |
        if [ ! -d "node_modules" ] || [ ! -d ~/.cache/puppeteer ]; then
          echo "Устанавливаем зависимости..."
          npm ci
          npx puppeteer browsers install chrome
        else
          echo "Зависимости уже установлены из кэша"
        fi

    - name: Run parser
      run: |
        node parser/puppeteer_parser.js

    - name: Commit results
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add results/prices.json
        git commit -m "🤖 Update prices $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
